"""Render Formula/qev.rb with one checksummed wheel resource per pinned package.

Homebrew downloads and verifies every wheel before building, so the install
step itself runs offline: a Python 3.12 venv, the wheels, then qev. Wheels are
chosen for CPython 3.12 on macOS 14+ arm64 (the oldest compatible build)::

    python packaging/homebrew/generate_formula.py \
        --source-url https://github.com/loadchange/qev/archive/refs/tags/v0.4.0.tar.gz \
        --source-sha256 <sha256> --output Formula/qev.rb
    python packaging/homebrew/generate_formula.py --source-tarball /tmp/qev.tar.gz --output /tmp/qev.rb
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
NO_DEPS = {"mlx-vlm": "0.7.1"}  # model code only; its audio/OpenCV/server extras stay out
MACOS = (14, 0)
TEMPLATE = '''class Qev < Formula
  desc "Typed decisions and multimodal chat from a local Qwen3.5 model on Apple Silicon"
  homepage "https://github.com/loadchange/qev"
  url "{url}"
  sha256 "{sha256}"
  license "Apache-2.0"
  head "https://github.com/loadchange/qev.git", branch: "main"
{bottle}
  depends_on arch: :arm64
  depends_on macos: :sonoma
  depends_on "python@3.12"

  # Generated by packaging/homebrew/generate_formula.py from requirements.txt;
  # do not edit by hand.
{resources}
  def install
    python = Formula["python@3.12"].opt_bin/"python3.12"
    system python, "-m", "venv", libexec
    wheels = buildpath/"wheels"
    wheels.mkpath
    resources.each do |r|
      r.fetch
      cp r.cached_download, wheels/File.basename(r.url)
    end
    pip = libexec/"bin/pip"
    system pip, "install", "--no-index", "--no-deps", "--no-cache-dir", *wheels.children
    system pip, "install", "--no-index", "--no-deps", "--no-build-isolation", "--no-cache-dir", buildpath
    bin.install_symlink libexec/"bin/qev"
  end

  def caveats
    <<~EOS
      Download and verify the model (3.5 GB) into ~/.qev once:
        qev pull
      Then ask directly, or keep the model warm in the background:
        qev decide "Card declined twice at checkout" -i "Which team?" --choice billing technical account
        brew services start qev
    EOS
  end

  service do
    run [opt_bin/"qev", "serve", "--no-request-log", "--decision-weights", "{decision_weights}"]
    keep_alive true
    working_dir var
    log_path var/"log/qev.log"
    error_log_path var/"log/qev.log"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/qev --version")
    system libexec/"bin/python", "-c", "import mlx.core, mlx_vlm.models.qwen3_5, qev.mlx_runtime, qev.processing"
    assert_match "qev-0.8b", shell_output("#{{bin}}/qev list")
  end
end
'''
_WHEEL = re.compile(r"^(?P<dist>.+?)-(?P<ver>[^-]+)(-\d[^-]*)?-(?P<py>[^-]+)-(?P<abi>[^-]+)-(?P<plat>[^-]+)\.whl$")


def pinned():
    packages = []
    for line in (HERE / "requirements.txt").read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            name, version = line.split("==")
            packages.append((name, version))
    return packages + sorted(NO_DEPS.items())


def compatible(filename):
    match = _WHEEL.match(filename)
    if not match:
        return None
    python_tags, abi, platforms = match["py"].split("."), match["abi"], match["plat"].split(".")
    if not ({"cp312", "py3", "py312"} & set(python_tags) or (abi == "abi3" and any(
            tag.startswith("cp3") and int(tag[3:]) <= 12 for tag in python_tags))):
        return None
    if abi not in ("none", "abi3", "cp312"):
        return None
    best = None
    for platform in platforms:
        if platform == "any":
            best = max(best or (0, 0), (0, 0))
        found = re.fullmatch(r"macosx_(\d+)_(\d+)_(arm64|universal2)", platform)
        if found and (int(found[1]), int(found[2])) <= MACOS:
            best = max(best or (0, 0), (int(found[1]), int(found[2])))
    return best


def choose(name, version):
    with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json", timeout=30) as response:
        files = json.load(response)["urls"]
    options = [(compatible(f["filename"]), f) for f in files if f["packagetype"] == "bdist_wheel"]
    options = [(rank, f) for rank, f in options if rank is not None]
    if not options:
        raise ValueError(f"No CPython 3.12 macOS arm64 wheel for {name}=={version}")
    _, chosen = max(options, key=lambda item: item[0])
    return chosen["url"], chosen["digests"]["sha256"]


def bottle_block(path):
    """`brew bottle --json` output -> a bottle do ... end block."""
    if path is None:
        return ""
    document = next(iter(json.loads(Path(path).read_text()).values()))["bottle"]
    lines = ["", "  bottle do", f'    root_url "{document["root_url"]}"']
    for tag, entry in sorted(document["tags"].items()):
        lines.append(f'    sha256 cellar: :{document["cellar"].lstrip(":")}, {tag}: "{entry["sha256"]}"'
                     if document["cellar"].startswith(":")
                     else f'    sha256 cellar: "{document["cellar"]}", {tag}: "{entry["sha256"]}"')
    return "\n".join([*lines, "  end", ""]) + "\n"


def render(url, sha256, decision_weights, bottle=None):
    blocks = []
    for name, version in pinned():
        wheel_url, digest = choose(name, version)
        blocks.append(f'  resource "{name}" do\n    url "{wheel_url}"\n    sha256 "{digest}"\n  end\n')
    return TEMPLATE.format(url=url, sha256=sha256, resources="\n".join(blocks), decision_weights=decision_weights,
                           bottle=bottle_block(bottle))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    source = ap.add_mutually_exclusive_group(required=True)
    source.add_argument("--source-url")
    source.add_argument("--source-tarball", type=Path, help="Local release tarball (file:// URL, for testing)")
    ap.add_argument("--source-sha256")
    ap.add_argument("--decision-weights", default="merged-bf16", choices=["adapter", "merged", "merged-bf16"])
    ap.add_argument("--bottle-json", type=Path, help="`brew bottle --json` output to embed")
    ap.add_argument("--output", type=Path, required=True)
    args = ap.parse_args(argv)
    if args.source_tarball:
        url = args.source_tarball.resolve().as_uri()
        digest = hashlib.sha256(args.source_tarball.read_bytes()).hexdigest()
    else:
        if not args.source_sha256:
            ap.error("--source-url needs --source-sha256")
        url, digest = args.source_url, args.source_sha256
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(url, digest, args.decision_weights, args.bottle_json))
    print(args.output)


if __name__ == "__main__":
    main()
